version: '3'

services:
  db:
    image: postgres:11
    volumes:
      - ./db:/var/lib/postgresql/data

  env:
    build: .
    volumes:
      - .:/env
    ports:
      - "8888:8888"
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres@acoustic-keylogger-research_db_1:5432
    depends_on:
      - db

