version: 2
jobs:
  build:
    docker:
      - image: circleci/python3.6.8

    working_directory: ~/acoustic-keylogger-research

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
            key: v1-dependecies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest -q src/test_dataman

      - store_artifacts:
          path: test-reports
          destination: test-reports

