version: 2
jobs:
  build:
    machine: true
    working_directory: ~/acoustic-keylogger-research

    steps:
      - checkout

      - restore_cache:
          keys:
            - >
                v1-dependencies-
                {{ checksum "docker-compose.yml" }}-
                {{ checksum "Dockerfile" }}-
                {{ checksum "requirements.txt" }}
            - v1-dependencies-

      - run: 
          name: build docker-compose
          command: docker-compose build
      - run:
          name: spin up docker-compose
          command: docker-compose up -d

      - save_cache:
          paths:
            - ./cache
          key: >
                v1-dependencies-
                {{ checksum "docker-compose.yml" }}-
                {{ checksum "Dockerfile" }}-
                {{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: docker-compose run env pytest -q tests
