version: 2
jobs:
  generate_cache:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys: 
            - >
                docker-compose-
                {{ .Branch  }}-
                {{ checksum ".circleci/config.yml" }}-
                {{ checksum "docker-compose.yml" }}-
                {{ checksum "Dockerfile" }}-
                {{ checksum "requirements.txt" }}
            - v1-dependencies-
          paths: ~/cache/images.tar
      - run:
          name: Generate cache if cache not found
          command: |
            if [ ! -f ~/cache/images.tar ]; then
              docker-compose build
              mkdir -p ~/cache
              docker save $(docker images -q) -o ~/cache/images.tar
            fi
      - save_cache:
          key: >
                docker-compose-
                {{ .Branch  }}-
                {{ checksum ".circleci/config.yml" }}-
                {{ checksum "docker-compose.yml" }}-
                {{ checksum "Dockerfile" }}-
                {{ checksum "requirements.txt" }}
          paths: ~/cache/images.tar

  testing:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys:
            - >
                docker-compose-
                {{ .Branch  }}-
                {{ checksum ".circleci/config.yml" }}-
                {{ checksum "docker-compose.yml" }}-
                {{ checksum "Dockerfile" }}-
                {{ checksum "requirements.txt" }}
            - v1-dependencies-
          paths: ~/cache/images.tar
      - run:
          name: Load Docker images
          command: docker load -i ~/cache/images.tar
      - run:
          name: Spin up Docker Compose
          command: docker-compose up -d
      - run:
          name: Run tests
          command: docker-compose run env pytest -q tests

workflows:
  version: 2
  build:
    jobs:
      - generate_cache
      - testing:
          requires:
            - generate_cache
